width: 800
height: 600
fullscreen: false

stencil_on: true # turns on or off stencil buffer filter
stencil_radius: 20 # pixels
stencil_opacity: 50 # higher is darker
stencil_angle: 45 # stencil triangle angle, higher means fov is increased
stencil_triangle_brightness: 80 # higher will make fov brighter


cursor_type: 2 # de 0 a 3
cursor_size: 23 # pixeles
cursor_source_file: "../sprites/gfx/pointer.bmp"

background:
 - ["aztec", "../sprites/gfx/backgrounds/aztec.png"]
 - ["inferno", "../sprites/gfx/backgrounds/inferno.png"]
 - ["office", "../sprites/gfx/backgrounds/office.png"]
 - ["space", "../sprites/gfx/backgrounds/space.jpg"]
 - ["water2", "../sprites/gfx/backgrounds/water2.jpg"]
 - ["blood", "../sprites/gfx/backgrounds/blood.jpg"]
 - ["lava", "../sprites/gfx/backgrounds/lava.jpg"]
 - ["sand1", "../sprites/gfx/backgrounds/sand1.jpg"]
 - ["stone1", "../sprites/gfx/backgrounds/stone1.jpg"]
 - ["water3", "../sprites/gfx/backgrounds/water3.jpg"]
 - ["dust", "../sprites/gfx/backgrounds/dust.png"]
 - ["mars", "../sprites/gfx/backgrounds/mars.png"]
 - ["sand1-night", "../sprites/gfx/backgrounds/sand1-night.jpg"]
 - ["toxic", "../sprites/gfx/backgrounds/toxic.jpg"]
 - ["water4", "../sprites/gfx/backgrounds/water4.jpg"]
 - ["gras1", "../sprites/gfx/backgrounds/gras1.jpg"]
 - ["nuke", "../sprites/gfx/backgrounds/nuke.png"]
 - ["snow", "../sprites/gfx/backgrounds/snow.jpg"]
 - ["water1", "../sprites/gfx/backgrounds/water1.jpg"]

walls:
 - ["wall_1" , "../sprites/map/wall_1_client.png"]
 - ["wall_2" , "../sprites/map/wall_2_client.png"]
 - ["wall_3" , "../sprites/map/wall_3_client.png"]
 - ["wall_4" , "../sprites/map/wall_4_client.png"]
 - ["wall_5" , "../sprites/map/wall_5_client.png"]
 - ["wall_6" , "../sprites/map/wall_6_client.png"]
 - ["wall_7" , "../sprites/map/wall_7_client.png"]
 - ["wall_8" , "../sprites/map/wall_8_client.png"]

weapons:
 - ["bomb", "../sprites/map/weapon_bomb.png"]
 - ["knife", "../sprites/map/weapon_knife.png"]
 - ["glock", "../sprites/map/weapon_glock.png"]
 - ["AK-47", "../sprites/map/weapon_ak47.png"]
 - ["m3", "../sprites/map/weapon_m3.png"]
 - ["AWP", "../sprites/map/weapon_awp.png"]
zones:
 - ["zoneA", "../sprites/map/zone_a.png"]
 - ["zoneB", "../sprites/map/zone_b.png"]
 - ["zoneBomb", "../sprites/map/zone_bomb.png"]
