types: ["background", "walls", "weapons", "zones"]

background:
 - ["aztec", "/var/cs2d/sprites/gfx/backgrounds/aztec.png"]
 - ["inferno", "/var/cs2d/sprites/gfx/backgrounds/inferno.png"]
 - ["office", "/var/cs2d/sprites/gfx/backgrounds/office.png"]
 - ["space", "/var/cs2d/sprites/gfx/backgrounds/space.jpg"]
 - ["water2", "/var/cs2d/sprites/gfx/backgrounds/water2.jpg"]
 - ["blood", "/var/cs2d/sprites/gfx/backgrounds/blood.jpg"]
 - ["lava", "/var/cs2d/sprites/gfx/backgrounds/lava.jpg"]
 - ["sand1", "/var/cs2d/sprites/gfx/backgrounds/sand1.jpg"]
 - ["stone1", "/var/cs2d/sprites/gfx/backgrounds/stone1.jpg"]
 - ["water3", "/var/cs2d/sprites/gfx/backgrounds/water3.jpg"]
 - ["dust", "/var/cs2d/sprites/gfx/backgrounds/dust.png"]
 - ["mars", "/var/cs2d/sprites/gfx/backgrounds/mars.png"]
 - ["sand1-night", "/var/cs2d/sprites/gfx/backgrounds/sand1-night.jpg"]
 - ["toxic", "/var/cs2d/sprites/gfx/backgrounds/toxic.jpg"]
 - ["water4", "/var/cs2d/sprites/gfx/backgrounds/water4.jpg"]
 - ["gras1", "/var/cs2d/sprites/gfx/backgrounds/gras1.jpg"]
 - ["nuke", "/var/cs2d/sprites/gfx/backgrounds/nuke.png"]
 - ["snow", "/var/cs2d/sprites/gfx/backgrounds/snow.jpg"]
 - ["water1", "/var/cs2d/sprites/gfx/backgrounds/water1.jpg"]

walls:
 - ["wall_1" , "/var/cs2d/sprites/map/wall_1.png"]
 - ["wall_2" , "/var/cs2d/sprites/map/wall_2.png"]
 - ["wall_3" , "/var/cs2d/sprites/map/wall_3.png"]
 - ["wall_4" , "/var/cs2d/sprites/map/wall_4.png"]
 - ["wall_5" , "/var/cs2d/sprites/map/wall_5.png"]
 - ["wall_6" , "/var/cs2d/sprites/map/wall_6.png"]
 - ["wall_7" , "/var/cs2d/sprites/map/wall_7.png"]
 - ["wall_8" , "/var/cs2d/sprites/map/wall_8.png"]

weapons:
 - ["bomb", "/var/cs2d/sprites/map/weapon_bomb.png"]
 - ["knife", "/var/cs2d/sprites/map/weapon_knife.png"]
 - ["glock", "/var/cs2d/sprites/map/weapon_glock.png"]
 - ["AK-47", "/var/cs2d/sprites/map/weapon_ak47.png"]
 - ["m3", "/var/cs2d/sprites/map/weapon_m3.png"]
 - ["AWP", "/var/cs2d/sprites/map/weapon_awp.png"]
zones:
 - ["zoneA", "/var/cs2d/sprites/map/zone_a.png"]
 - ["zoneB", "/var/cs2d/sprites/map/zone_b.png"]
 - ["zoneBomb", "/var/cs2d/sprites/map/zone_bomb.png"]
