# distancias en centimetros
# tiempo en ticks

player_hp: 100 # vida maxima
starting_money: 800

match_max_players: 10

# accuracy en pistol/awp/rifle determina la distancia macima de la trayectoria al enemigo 
# accuracy en shorgun/knife determina el spread
# las armas sin firerate disparan nuevamente cuando se hace click

pistol_ammo: 8
pistol_range: 2000
pistol_accuracy: 50
pistol_damage: 20
pistol_bounty: 300

awp_price: 4750
awp_ammo: 10
awp_range: 50000
awp_accuracy: 25
awp_damage: 100
awp_firerate: 60
awp_bounty: 100

rifle_price: 2700
rifle_ammo: 30
rifle_range: 1000
rifle_accuracy: 25
rifle_damage: 25
rifle_firerate: 24
rifle_bounty: 300

shotgun_price: 1800
shotgun_ammo: 2
shotgun_range: 900
shotgun_accuracy: 30
shotgun_damage: 100
shotgun_bounty: 500

knife_range: 150
knife_accuracy: 60
knife_damage: 20
knife_firerate: 30
knife_bounty: 1000

money_round_won: 100
money_round_lost: 500

bomb_range: 150
bomb_accuracy: 60
bomb_damage: 5
bomb_firerate: 30
bomb_fuse: 600
bomb_activate_time: 120
bomb_bounty: 50