#ifndef CONFIGVARIABLES_H
#define CONFIGVARIABLES_H


enum ConfigVariables {
    PLAYER_HP,
    STARTING_MONEY,
    MAX_PLAYERS,
    PISTOL_AMMO,
    PISTOL_RANGE,
    PISTOL_ACCURACY,
    PISTOL_DAMAGE,
    PISTOL_BOUNTY,
    AWP_PRICE,
    AWP_AMMO,
    AWP_RANGE,
    AWP_ACCURACY,
    AWP_DAMAGE,
    AWP_FIRERATE,
    AWP_BOUNTY,
    RIFLE_PRICE,
    RIFLE_AMMO,
    RIFLE_RANGE,
    RIFLE_ACCURACY,
    RIFLE_DAMAGE,
    RIFLE_FIRERATE,
    RIFLE_BOUNTY,
    SHOTGUN_PRICE,
    SHOTGUN_AMMO,
    SHOTGUN_RANGE,
    SHOTGUN_ACCURACY,
    SHOTGUN_DAMAGE,
    SHOTGUN_BOUNTY,
    KNIFE_RANGE,
    KNIFE_ACCURACY,
    KNIFE_DAMAGE,
    KNIFE_FIRERATE,
    KNIFE_BOUNTY,
    MONEY_ROUND_WON,
    MONEY_ROUND_LOST,
    BOMB_RANGE,
    BOMB_ACCURACY,
    BOMB_DAMAGE,
    BOMB_FIRERATE,
    BOMB_FUSE,
    BOMB_ACTIVATE_TIME,
    BOMB_BOUNTY
};


#endif
